import 'dotenv/config'
import fs from 'fs'
import path from 'path'
import { getPayload } from 'payload'
import config from '../src/payload.config'

// One-off: uploads white-key background-removed versions of product gallery
// photos (generated by scripts/../scratchpad/batch_whitekey.py from R2
// originals) as new Media docs, then repoints each product's gallery `image`
// field at the new doc. Originals are left untouched in `media`/R2 — nothing
// is overwritten or deleted, so this is fully reversible by pointing gallery
// rows back at the original media ids recorded in the manifest.
const SCRATCH = process.env.TRANSPARENT_IMAGES_SCRATCH
if (!SCRATCH) throw new Error('Set TRANSPARENT_IMAGES_SCRATCH to the scratchpad dir path')

type ManifestEntry = { mediaId: number; origFilename: string; alt: string; outFile: string }

const run = async () => {
  const payload = await getPayload({ config })
  const manifestFile = process.env.TRANSPARENT_IMAGES_MANIFEST || 'whitekey_manifest.json'
  const manifest: ManifestEntry[] = JSON.parse(
    fs.readFileSync(path.join(SCRATCH, manifestFile), 'utf-8'),
  )

  const mapFile = path.join(SCRATCH, `old_to_new_media_ids.${manifestFile}`)
  const oldToNew = new Map<number, number>(
    fs.existsSync(mapFile)
      ? (Object.entries(JSON.parse(fs.readFileSync(mapFile, 'utf-8'))).map(([k, v]) => [
          Number(k),
          v as number,
        ]) as [number, number][])
      : [],
  )
  const uploadFailures: Array<{ mediaId: number; error: string }> = []

  for (const [i, entry] of manifest.entries()) {
    if (oldToNew.has(entry.mediaId)) continue // resume support: already uploaded in a prior run

    const filePath = path.join(SCRATCH, 'transparent_all', entry.outFile)
    const buffer = fs.readFileSync(filePath)
    const newFilename = entry.origFilename.replace(/\.[^./]+$/, '') + '-transparent.png'

    try {
      const created = await payload.create({
        collection: 'media',
        data: { alt: entry.alt },
        file: {
          data: buffer,
          mimetype: 'image/png',
          name: newFilename,
          size: buffer.length,
        },
        overrideAccess: true,
      })

      oldToNew.set(entry.mediaId, created.id)
      fs.writeFileSync(mapFile, JSON.stringify(Object.fromEntries(oldToNew), null, 2))
      payload.logger.info(
        `[${i + 1}/${manifest.length}] uploaded media ${entry.mediaId} -> ${created.id} (${newFilename})`,
      )
    } catch (error) {
      uploadFailures.push({ mediaId: entry.mediaId, error: error instanceof Error ? error.message : String(error) })
      payload.logger.error(`[${i + 1}/${manifest.length}] FAILED media ${entry.mediaId}: ${error}`)
    }
  }

  if (uploadFailures.length > 0) {
    fs.writeFileSync(
      path.join(SCRATCH, 'upload_failures.json'),
      JSON.stringify(uploadFailures, null, 2),
    )
  }

  const products = await payload.find({
    collection: 'products',
    depth: 0,
    limit: 0,
    overrideAccess: true,
  })

  let updatedProductCount = 0
  for (const product of products.docs) {
    const gallery = (product.gallery ?? []) as Array<{ id?: string; image: number }>
    let changed = false
    const newGallery = gallery.map((row) => {
      const mapped = oldToNew.get(row.image)
      if (mapped) {
        changed = true
        return { ...row, image: mapped }
      }
      return row
    })

    if (changed) {
      await payload.update({
        collection: 'products',
        id: product.id,
        data: { gallery: newGallery },
        overrideAccess: true,
      })
      updatedProductCount += 1
      payload.logger.info(`updated product ${product.id} (${product.title})`)
    }
  }

  payload.logger.info(`Done. ${oldToNew.size} media uploaded, ${updatedProductCount} products repointed.`)
  process.exit(0)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
