/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    datasheets: Datasheet;
    guides: Guide;
    brands: Brand;
    reviews: Review;
    services: Service;
    'newsletter-subscribers': NewsletterSubscriber;
    coupons: Coupon;
    'gift-cards': GiftCard;
    'stock-alerts': StockAlert;
    'return-requests': ReturnRequest;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    datasheets: DatasheetsSelect<false> | DatasheetsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'gift-cards': GiftCardsSelect<false> | GiftCardsSelect<true>;
    'stock-alerts': StockAlertsSelect<false> | StockAlertsSelect<true>;
    'return-requests': ReturnRequestsSelect<false> | ReturnRequestsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'feature-flags': FeatureFlag;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Profile picture, shown in the account area and header.
   */
  avatar?: (number | null) | Media;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'INR' | null;
  accessToken?: string | null;
  /**
   * Carrier tracking number (AWB), shown to the customer on their order. Auto-filled by the Shiprocket integration once a courier is assigned — editable manually as a fallback.
   */
  trackingNumber?: string | null;
  /**
   * Courier Shiprocket assigned to this shipment.
   */
  courierName?: string | null;
  /**
   * Latest status from Shiprocket (e.g. "Pickup Scheduled", "In Transit", "Delivered").
   */
  shipmentStatus?: string | null;
  shiprocketOrderId?: string | null;
  shiprocketShipmentId?: string | null;
  paymentMethod?: ('card' | 'cod' | 'gift-card') | null;
  /**
   * Internal guard — prevents double-processing coupon/gift-card redemption.
   */
  discountsApplied?: boolean | null;
  couponApplied?: {
    code?: string | null;
    discountAmount?: number | null;
  };
  giftCardApplied?: {
    code?: string | null;
    amountApplied?: number | null;
  };
  /**
   * Basic app-level fraud heuristic (high-value guest order). PayU screens the payment itself separately.
   */
  flaggedForReview?: boolean | null;
  flagReason?: string | null;
  /**
   * GST split computed at order creation from SiteSettings.taxSettings — snapshotted so later rate/state changes don’t retroactively alter past invoices.
   */
  taxBreakdown?: {
    taxType?: ('intra-state' | 'inter-state') | null;
    gstRatePercent?: number | null;
    taxableValue?: number | null;
    cgstAmount?: number | null;
    sgstAmount?: number | null;
    igstAmount?: number | null;
    totalTax?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Short key-feature bullets shown near the top of the product page (e.g. "AC output: 1800W continuous, 2700W surge").
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        variantOption?: (number | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  /**
   * Downloadable PDF datasheets / spec sheets for this product.
   */
  datasheets?: (number | Datasheet)[] | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInINREnabled?: boolean | null;
  priceInINR?: number | null;
  /**
   * Generic merchandising cross-sell (e.g. "customers also viewed").
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * Technically compatible products (e.g. motor ↔ ESC ↔ props). Distinct from Related Products, which is generic merchandising.
   */
  compatibleProducts?: (number | Product)[] | null;
  /**
   * Optional bulk/reseller pricing tiers by minimum quantity (e.g. hobbyist vs reseller quantities). Data-only for now — checkout price resolution reads this in a later phase.
   */
  priceTiers?:
    | {
        minQuantity: number;
        priceInINR: number;
        id?: string | null;
      }[]
    | null;
  specs?: {
    /**
     * Shown when Spec Schema is set to "Drone Motors".
     */
    droneMotor?: {
      motorType?: ('brushless' | 'brushed') | null;
      /**
       * Motor KV rating (RPM per volt).
       */
      kvRating?: number | null;
      statorWidthMM?: number | null;
      statorHeightMM?: number | null;
      weightG?: number | null;
      /**
       * Structured throttle → thrust data points (keeps thrust data queryable/sortable).
       */
      thrustCurve?:
        | {
            throttlePercent: number;
            thrustGramForce: number;
            propModel?: string | null;
            id?: string | null;
          }[]
        | null;
      applications?: ('racing' | 'freestyle' | 'cinematic' | 'industrial-agriculture')[] | null;
    };
    /**
     * Shown when Spec Schema is set to "Single-Board Computers".
     */
    sbc?: {
      modelFamily?:
        | ('raspberry-pi-zero' | 'raspberry-pi-3' | 'raspberry-pi-4' | 'raspberry-pi-5' | 'raspberry-pi-cm' | 'other')
        | null;
      modelFamilyOther?: string | null;
      formFactor?: ('standard' | 'zero' | 'compute-module' | 'other') | null;
      formFactorOther?: string | null;
      ramMB?: ('512' | '1024' | '2048' | '4096' | '8192' | '16384' | 'custom') | null;
      ramCustomMB?: number | null;
      connectivity?: ('wifi' | 'bluetooth' | 'ethernet' | 'usb-c' | 'usb-a')[] | null;
      gpioPinCount?: number | null;
      gpioLayoutNotes?: string | null;
    };
    /**
     * Shown when Spec Schema is set to "Microcontrollers & Dev Boards".
     */
    microcontroller?: {
      family?: ('arduino' | 'esp32' | 'esp8266' | 'stm32' | 'pic' | 'teensy' | 'rp2040' | 'nrf52' | 'other') | null;
      familyOther?: string | null;
      clockSpeedMHz?: number | null;
      flashSize?: number | null;
      flashUnit?: ('KB' | 'MB') | null;
      ramSize?: number | null;
      ramUnit?: ('KB' | 'MB') | null;
      ioCount?: number | null;
      wireless?: ('wifi' | 'bluetooth' | 'ble' | 'lora' | 'zigbee' | 'none')[] | null;
    };
    /**
     * Shown when Spec Schema is set to "Mechanical Components".
     */
    mechanical?: {
      componentType?: ('gear' | 'bearing' | 'coupler' | 'frame' | 'chassis-kit' | 'fastener' | 'other') | null;
      componentTypeOther?: string | null;
      material?: ('aluminum' | 'carbon-fiber' | 'abs-plastic' | 'nylon' | 'steel' | 'brass' | 'pla' | 'other') | null;
      materialOther?: string | null;
      dimensions?: {
        lengthMM?: number | null;
        widthMM?: number | null;
        heightMM?: number | null;
        boreDiameterMM?: number | null;
      };
    };
    /**
     * Shown when Spec Schema is set to "Workbench Tools".
     */
    tool?: {
      toolType?:
        ('soldering-station' | 'multimeter' | 'oscilloscope' | 'hot-air-rework' | 'hand-tool' | 'other') | null;
      powerWattage?: number | null;
      /**
       * Free text, e.g. "110-240V AC" — voltage notation varies too much for a clean enum.
       */
      voltageSpec?: string | null;
      /**
       * Generic, repeatable parameter/min/max/unit rows — mirrors how datasheets tabulate ranges and works the same across every tool type (multimeter, oscilloscope, iron, etc).
       */
      measurementRanges?:
        | {
            parameter?:
              | (
                  | 'temperature'
                  | 'voltage-dc'
                  | 'voltage-ac'
                  | 'current'
                  | 'resistance'
                  | 'bandwidth'
                  | 'sample-rate'
                  | 'airflow'
                  | 'other'
                )
              | null;
            parameterOther?: string | null;
            minValue?: number | null;
            maxValue?: number | null;
            unit?: ('°C' | 'V' | 'A' | 'Ω' | 'MHz' | 'MS/s' | 'L/min' | 'other') | null;
            unitOther?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Shown when Spec Schema is set to "3D Printing Filaments".
     */
    filament?: {
      materialType?: ('pla' | 'petg' | 'abs' | 'tpu' | 'nylon' | 'other') | null;
      materialTypeOther?: string | null;
      diameterMM?: ('1.75' | '2.85') | null;
      color?: string | null;
      /**
       * Optional hex value for a future color swatch.
       */
      colorHex?: string | null;
      spoolWeightG?: number | null;
      printTempMinC?: number | null;
      printTempMaxC?: number | null;
    };
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  categories?: (number | Category)[] | null;
  brand?: (number | null) | Brand;
  /**
   * Freeform tags for search and merchandising.
   */
  tags?: string[] | null;
  /**
   * Surface this product in curated spots like the mega-menu and homepage.
   */
  featured?: boolean | null;
  /**
   * Which category spec schema to show on the Product Details tab.
   */
  specSchemaType?: ('none' | 'drone-motors' | 'sbc' | 'microcontrollers' | 'mechanical' | 'tools' | 'filaments') | null;
  /**
   * Auto-derived from Inventory on save, unless set to "Backorder" (which is a manual business decision and is left alone).
   */
  stockStatus?: ('in-stock' | 'low-stock' | 'out-of-stock' | 'backorder') | null;
  /**
   * Inventory at or below this triggers "Low Stock". Defaults to 5.
   */
  lowStockThreshold?: number | null;
  /**
   * Per-unit shipping weight in grams. Used for Shiprocket rate checks and shipment creation — defaults to 50g, a reasonable estimate for small electronic components.
   */
  weightInGrams?: number | null;
  /**
   * Optional "was" price (₹) shown struck through next to the current price when higher than it.
   */
  compareAtPriceInINR?: number | null;
  /**
   * Flags this as a purchasable gift card — a GiftCard document (with a redeemable code) is minted per unit automatically when an order containing it is placed. Use variants for denominations.
   */
  isGiftCard?: boolean | null;
  leadTimeDays?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasheets".
 */
export interface Datasheet {
  id: number;
  title?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'illustrated';
    illustrationKey?:
      ('workshop' | 'drone-motors' | 'sbc' | 'microcontrollers' | 'mechanical' | 'tools' | 'filaments') | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
    | FAQBlock
    | ComparisonTableBlock
    | CustomerInteractionBlock
    | IllustratedCategoryGridBlock
    | HeroCarouselBlock
    | FlashDealBlock
    | TrendingProductsBlock
    | CategoryGridBlock
    | BrandStripBlock
    | ServicesShowcaseBlock
    | TrustBadgesStripBlock
    | TestimonialsBlock
    | FeaturedCollectionBlock
    | ContentFeedBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Optional parent category, for sub-category hierarchies.
   */
  parent?: (number | null) | Category;
  /**
   * Which spec schema products in this category use (should match the Spec Schema set on those Products).
   */
  specSchemaType?: ('none' | 'drone-motors' | 'sbc' | 'microcontrollers' | 'mechanical' | 'tools' | 'filaments') | null;
  layout?:
    | (CallToActionBlock | ContentBlock | MediaBlock | FAQBlock | ComparisonTableBlock | IllustratedCategoryGridBlock)[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  /**
   * Small label shown above the heading, e.g. "Support".
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Optional supporting sentence shown under the heading.
   */
  description?: string | null;
  /**
   * Optional "Still have questions?" support card shown next to the FAQ list.
   */
  contactCard?: {
    enabled?: boolean | null;
    heading?: string | null;
    description?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  heading?: string | null;
  /**
   * Pick 2-4 products to compare. Works best when they share a category spec schema.
   */
  products: (number | Product)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IllustratedCategoryGridBlock".
 */
export interface IllustratedCategoryGridBlock {
  heading?: string | null;
  categories: (number | Category)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'illustratedCategoryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomerInteractionBlock".
 */
export interface CustomerInteractionBlock {
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  channels?:
    | {
        type: 'quote' | 'technical' | 'tracking' | 'service';
        title: string;
        description?: string | null;
        responseTime?: string | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        label: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  primaryLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    label: string;
  };
  secondaryLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'customerInteraction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCarouselBlock".
 */
export interface HeroCarouselBlock {
  slides?:
    | {
        layout?: ('fullBleed' | 'split') | null;
        image: number | Media;
        /**
         * Optional — falls back to the image above if left empty.
         */
        mobileImage?: (number | null) | Media;
        /**
         * Optional small badge, e.g. "New" or "Limited stock".
         */
        badge?: string | null;
        heading: string;
        subheading?: string | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlashDealBlock".
 */
export interface FlashDealBlock {
  title: string;
  /**
   * e.g. "Up to 30% off"
   */
  discountBadge?: string | null;
  /**
   * The strip auto-hides once this passes.
   */
  endDate: string;
  populateBy?: ('collection' | 'selection') | null;
  categories?: (number | Category)[] | null;
  selectedProducts?: (number | Product)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flashDeal';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrendingProductsBlock".
 */
export interface TrendingProductsBlock {
  heading?: string | null;
  /**
   * Always shown first, in this order. Remaining slots auto-fill from recent sales.
   */
  pinnedProducts?: (number | Product)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trendingProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock".
 */
export interface CategoryGridBlock {
  heading?: string | null;
  /**
   * Order here controls display order. 6–8 categories works best on desktop.
   */
  categories?:
    | {
        category: number | Category;
        /**
         * Optional — falls back to a themed icon if left empty.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandStripBlock".
 */
export interface BrandStripBlock {
  /**
   * Optional, e.g. "Trusted by 140+ brands worldwide"
   */
  heading?: string | null;
  brands: (number | Brand)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesShowcaseBlock".
 */
export interface ServicesShowcaseBlock {
  heading?: string | null;
  services: (number | Service)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  icon?: (number | null) | Media;
  /**
   * One-line summary shown on the homepage Services Showcase card.
   */
  description?: string | null;
  /**
   * Longer description shown on the service info page.
   */
  body?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustBadgesStripBlock".
 */
export interface TrustBadgesStripBlock {
  /**
   * Leave empty to show sensible defaults (shipping, support, secure payment, returns).
   */
  badges?:
    | {
        icon: 'shipping' | 'support' | 'secure' | 'returns' | 'verified';
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustBadgesStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  populateBy?: ('manual' | 'reviews') | null;
  testimonials?:
    | {
        name: string;
        photo?: (number | null) | Media;
        /**
         * e.g. "Robotics student" or "Hobbyist maker"
         */
        role?: string | null;
        rating: number;
        quote: string;
        product?: (number | null) | Product;
        id?: string | null;
      }[]
    | null;
  /**
   * Only pull reviews rated at least this high.
   */
  minRating?: number | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCollectionBlock".
 */
export interface FeaturedCollectionBlock {
  /**
   * One panel per promo banner — 2 side-by-side works best.
   */
  panels?:
    | {
        image: number | Media;
        heading: string;
        copy?: string | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCollection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentFeedBlock".
 */
export interface ContentFeedBlock {
  heading: string;
  filterBy?: ('all' | 'article' | 'video') | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentFeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInINREnabled?: boolean | null;
  priceInINR?: number | null;
  /**
   * Optional bulk/reseller pricing tiers by minimum quantity (e.g. hobbyist vs reseller quantities). Data-only for now — checkout price resolution reads this in a later phase.
   */
  priceTiers?:
    | {
        minQuantity: number;
        priceInINR: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'payu' | null;
  payu?: {
    txnid?: string | null;
    mihpayid?: string | null;
    status?: string | null;
    shippingAddressSnapshot?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'INR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'INR' | null;
  /**
   * Coupon code applied to this cart, if any.
   */
  appliedCouponCode?: string | null;
  /**
   * Gift card code applied to this cart, if any.
   */
  appliedGiftCardCode?: string | null;
  /**
   * Auto-computed — amount deducted by the applied coupon.
   */
  couponDiscountAmount?: number | null;
  /**
   * Auto-computed — amount deducted by the applied gift card.
   */
  giftCardAmountApplied?: number | null;
  /**
   * Set once the abandoned-cart recovery email has been sent, so it only ever goes out once.
   */
  abandonedRecoveryEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * Thumbnail shown in the Tutorials/Blog feed and archive cards.
   */
  coverImage?: (number | null) | Media;
  /**
   * Short summary shown in card previews.
   */
  excerpt?: string | null;
  contentType?: ('article' | 'video') | null;
  /**
   * YouTube (or other) video URL, shown with a play-icon overlay.
   */
  videoUrl?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'illustrated';
    illustrationKey?:
      ('workshop' | 'drone-motors' | 'sbc' | 'microcontrollers' | 'mechanical' | 'tools' | 'filaments') | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
    | FAQBlock
    | ComparisonTableBlock
    | IllustratedCategoryGridBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Byline shown on the post. Plain text (not a Users relationship) since Users read access is admin-only — set this for posts that should appear on /blog.
   */
  authorName?: string | null;
  /**
   * e.g. "Supply Chain" or "People & Culture" — shown under the author name.
   */
  authorTitle?: string | null;
  /**
   * The category this guide/pillar page centers on, for topical linking.
   */
  relatedCategory?: (number | null) | Category;
  relatedProducts?: (number | Product)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  customer: number | User;
  rating: number;
  comment?: string | null;
  /**
   * Auto-derived from order history — cannot be set manually.
   */
  verifiedPurchase?: boolean | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  subscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Case-insensitive. Stored and matched upper-cased, e.g. "WELCOME10".
   */
  code: string;
  type: 'percentage' | 'fixed';
  /**
   * For percentage: 0-100. For fixed: an amount in the order currency.
   */
  value: number;
  /**
   * Only relevant for fixed-amount coupons — which currency the value is in.
   */
  currency?: 'INR' | null;
  /**
   * Minimum cart subtotal (in order currency) required to apply this coupon.
   */
  minOrderAmount?: number | null;
  /**
   * Leave blank for unlimited redemptions.
   */
  maxRedemptions?: number | null;
  redemptionCount?: number | null;
  expiresAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards".
 */
export interface GiftCard {
  id: number;
  /**
   * Redemption code — auto-generated, but editable for manually-issued cards.
   */
  code: string;
  initialAmount: number;
  /**
   * Remaining redeemable balance. Decremented automatically on redemption.
   */
  balance: number;
  currency: 'INR';
  /**
   * Who the card was issued to / purchased for.
   */
  recipientEmail?: string | null;
  purchasedBy?: (number | null) | User;
  /**
   * The order that purchased this gift card, if any.
   */
  sourceOrder?: (number | null) | Order;
  status?: ('active' | 'redeemed' | 'expired' | 'disabled') | null;
  expiresAt?: string | null;
  /**
   * Audit log of partial/full redemptions against this card.
   */
  redemptions?:
    | {
        orderRef?: (number | null) | Order;
        amount: number;
        redeemedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-alerts".
 */
export interface StockAlert {
  id: number;
  product: number | Product;
  variant?: (number | null) | Variant;
  email: string;
  /**
   * Set automatically once the notification email has been sent.
   */
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "return-requests".
 */
export interface ReturnRequest {
  id: number;
  order: number | Order;
  customerEmail: string;
  product?: (number | null) | Product;
  reason: 'damaged' | 'wrong-item' | 'not-as-described' | 'no-longer-needed' | 'other';
  description?: string | null;
  status?: ('requested' | 'approved' | 'rejected' | 'completed') | null;
  /**
   * Defaults to the full order amount when left blank. Review/adjust before setting status to Approved — that triggers the actual refund.
   */
  refundAmount?: number | null;
  refundStatus?: ('not-applicable' | 'processed' | 'failed' | 'manual-required') | null;
  refundNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'datasheets';
        value: number | Datasheet;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'gift-cards';
        value: number | GiftCard;
      } | null)
    | ({
        relationTo: 'stock-alerts';
        value: number | StockAlert;
      } | null)
    | ({
        relationTo: 'return-requests';
        value: number | ReturnRequest;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        illustrationKey?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        customerInteraction?: T | CustomerInteractionBlockSelect<T>;
        illustratedCategoryGrid?: T | IllustratedCategoryGridBlockSelect<T>;
        heroCarousel?: T | HeroCarouselBlockSelect<T>;
        flashDeal?: T | FlashDealBlockSelect<T>;
        trendingProducts?: T | TrendingProductsBlockSelect<T>;
        categoryGrid?: T | CategoryGridBlockSelect<T>;
        brandStrip?: T | BrandStripBlockSelect<T>;
        servicesShowcase?: T | ServicesShowcaseBlockSelect<T>;
        trustBadgesStrip?: T | TrustBadgesStripBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        featuredCollection?: T | FeaturedCollectionBlockSelect<T>;
        contentFeed?: T | ContentFeedBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  contactCard?:
    | T
    | {
        enabled?: T;
        heading?: T;
        description?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  heading?: T;
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomerInteractionBlock_select".
 */
export interface CustomerInteractionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  channels?:
    | T
    | {
        type?: T;
        title?: T;
        description?: T;
        responseTime?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        label?: T;
        detail?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  primaryLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  secondaryLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IllustratedCategoryGridBlock_select".
 */
export interface IllustratedCategoryGridBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCarouselBlock_select".
 */
export interface HeroCarouselBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        layout?: T;
        image?: T;
        mobileImage?: T;
        badge?: T;
        heading?: T;
        subheading?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlashDealBlock_select".
 */
export interface FlashDealBlockSelect<T extends boolean = true> {
  title?: T;
  discountBadge?: T;
  endDate?: T;
  populateBy?: T;
  categories?: T;
  selectedProducts?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrendingProductsBlock_select".
 */
export interface TrendingProductsBlockSelect<T extends boolean = true> {
  heading?: T;
  pinnedProducts?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock_select".
 */
export interface CategoryGridBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?:
    | T
    | {
        category?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandStripBlock_select".
 */
export interface BrandStripBlockSelect<T extends boolean = true> {
  heading?: T;
  brands?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesShowcaseBlock_select".
 */
export interface ServicesShowcaseBlockSelect<T extends boolean = true> {
  heading?: T;
  services?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustBadgesStripBlock_select".
 */
export interface TrustBadgesStripBlockSelect<T extends boolean = true> {
  badges?:
    | T
    | {
        icon?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  populateBy?: T;
  testimonials?:
    | T
    | {
        name?: T;
        photo?: T;
        role?: T;
        rating?: T;
        quote?: T;
        product?: T;
        id?: T;
      };
  minRating?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCollectionBlock_select".
 */
export interface FeaturedCollectionBlockSelect<T extends boolean = true> {
  panels?:
    | T
    | {
        image?: T;
        heading?: T;
        copy?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentFeedBlock_select".
 */
export interface ContentFeedBlockSelect<T extends boolean = true> {
  heading?: T;
  filterBy?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  specSchemaType?: T;
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        illustratedCategoryGrid?: T | IllustratedCategoryGridBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasheets_select".
 */
export interface DatasheetsSelect<T extends boolean = true> {
  title?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  coverImage?: T;
  excerpt?: T;
  contentType?: T;
  videoUrl?: T;
  hero?:
    | T
    | {
        type?: T;
        illustrationKey?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        illustratedCategoryGrid?: T | IllustratedCategoryGridBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  authorName?: T;
  authorTitle?: T;
  relatedCategory?: T;
  relatedProducts?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  customer?: T;
  rating?: T;
  comment?: T;
  verifiedPurchase?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  description?: T;
  body?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  subscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  currency?: T;
  minOrderAmount?: T;
  maxRedemptions?: T;
  redemptionCount?: T;
  expiresAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards_select".
 */
export interface GiftCardsSelect<T extends boolean = true> {
  code?: T;
  initialAmount?: T;
  balance?: T;
  currency?: T;
  recipientEmail?: T;
  purchasedBy?: T;
  sourceOrder?: T;
  status?: T;
  expiresAt?: T;
  redemptions?:
    | T
    | {
        orderRef?: T;
        amount?: T;
        redeemedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-alerts_select".
 */
export interface StockAlertsSelect<T extends boolean = true> {
  product?: T;
  variant?: T;
  email?: T;
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "return-requests_select".
 */
export interface ReturnRequestsSelect<T extends boolean = true> {
  order?: T;
  customerEmail?: T;
  product?: T;
  reason?: T;
  description?: T;
  status?: T;
  refundAmount?: T;
  refundStatus?: T;
  refundNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInINREnabled?: T;
  priceInINR?: T;
  priceTiers?:
    | T
    | {
        minQuantity?: T;
        priceInINR?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  datasheets?: T;
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInINREnabled?: T;
  priceInINR?: T;
  relatedProducts?: T;
  compatibleProducts?: T;
  priceTiers?:
    | T
    | {
        minQuantity?: T;
        priceInINR?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        droneMotor?:
          | T
          | {
              motorType?: T;
              kvRating?: T;
              statorWidthMM?: T;
              statorHeightMM?: T;
              weightG?: T;
              thrustCurve?:
                | T
                | {
                    throttlePercent?: T;
                    thrustGramForce?: T;
                    propModel?: T;
                    id?: T;
                  };
              applications?: T;
            };
        sbc?:
          | T
          | {
              modelFamily?: T;
              modelFamilyOther?: T;
              formFactor?: T;
              formFactorOther?: T;
              ramMB?: T;
              ramCustomMB?: T;
              connectivity?: T;
              gpioPinCount?: T;
              gpioLayoutNotes?: T;
            };
        microcontroller?:
          | T
          | {
              family?: T;
              familyOther?: T;
              clockSpeedMHz?: T;
              flashSize?: T;
              flashUnit?: T;
              ramSize?: T;
              ramUnit?: T;
              ioCount?: T;
              wireless?: T;
            };
        mechanical?:
          | T
          | {
              componentType?: T;
              componentTypeOther?: T;
              material?: T;
              materialOther?: T;
              dimensions?:
                | T
                | {
                    lengthMM?: T;
                    widthMM?: T;
                    heightMM?: T;
                    boreDiameterMM?: T;
                  };
            };
        tool?:
          | T
          | {
              toolType?: T;
              powerWattage?: T;
              voltageSpec?: T;
              measurementRanges?:
                | T
                | {
                    parameter?: T;
                    parameterOther?: T;
                    minValue?: T;
                    maxValue?: T;
                    unit?: T;
                    unitOther?: T;
                    id?: T;
                  };
            };
        filament?:
          | T
          | {
              materialType?: T;
              materialTypeOther?: T;
              diameterMM?: T;
              color?: T;
              colorHex?: T;
              spoolWeightG?: T;
              printTempMinC?: T;
              printTempMaxC?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  brand?: T;
  tags?: T;
  featured?: T;
  specSchemaType?: T;
  stockStatus?: T;
  lowStockThreshold?: T;
  weightInGrams?: T;
  compareAtPriceInINR?: T;
  isGiftCard?: T;
  leadTimeDays?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  appliedCouponCode?: T;
  appliedGiftCardCode?: T;
  couponDiscountAmount?: T;
  giftCardAmountApplied?: T;
  abandonedRecoveryEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  accessToken?: T;
  trackingNumber?: T;
  courierName?: T;
  shipmentStatus?: T;
  shiprocketOrderId?: T;
  shiprocketShipmentId?: T;
  paymentMethod?: T;
  discountsApplied?: T;
  couponApplied?:
    | T
    | {
        code?: T;
        discountAmount?: T;
      };
  giftCardApplied?:
    | T
    | {
        code?: T;
        amountApplied?: T;
      };
  flaggedForReview?: T;
  flagReason?: T;
  taxBreakdown?:
    | T
    | {
        taxType?: T;
        gstRatePercent?: T;
        taxableValue?: T;
        cgstAmount?: T;
        sgstAmount?: T;
        igstAmount?: T;
        totalTax?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  payu?:
    | T
    | {
        txnid?: T;
        mihpayid?: T;
        status?: T;
        shippingAddressSnapshot?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        /**
         * Optional sub-links — turns this item into a dropdown menu.
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * e.g. "to get promotional offers & discounts"
   */
  newsletterHeading?: string | null;
  newsletterCopy?: string | null;
  /**
   * Link columns, e.g. "Information", "My Account", "Services", "Policies".
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy flat link row, kept for backward compatibility — prefer Columns above.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcementBar?: {
    /**
     * Rotates automatically when more than one message is present.
     */
    messages?:
      | {
          text: string;
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    dismissible?: boolean | null;
    rotateSeconds?: number | null;
  };
  organizationName?: string | null;
  /**
   * Shown in the header utility bar, e.g. "1800 266 6123".
   */
  supportPhone?: string | null;
  /**
   * Shown for bulk order / B2B inquiries on product pages, e.g. "sales@Picmychip.com".
   */
  supportEmail?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * e.g. 2020-01-01
   */
  foundingDate?: string | null;
  /**
   * Used to generate printable GST tax invoices on orders. Confirm the applicable GST treatment with your tax advisor — this only formats what you configure here.
   */
  taxSettings?: {
    gstin?: string | null;
    businessName?: string | null;
    businessAddress?: string | null;
    /**
     * Used to label the tax split as CGST+SGST (intra-state) vs IGST (inter-state).
     */
    businessState?: string | null;
    /**
     * Applied rate, assumed inclusive in listed prices.
     */
    gstRatePercent?: number | null;
  };
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Toggle storefront features on/off without a deploy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: number;
  cashOnDelivery?: boolean | null;
  giftCards?: boolean | null;
  coupons?: boolean | null;
  backInStockAlerts?: boolean | null;
  recentlyViewed?: boolean | null;
  searchAutocomplete?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  newsletterHeading?: T;
  newsletterCopy?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        messages?:
          | T
          | {
              text?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
            };
        dismissible?: T;
        rotateSeconds?: T;
      };
  organizationName?: T;
  supportPhone?: T;
  supportEmail?: T;
  logo?: T;
  description?: T;
  foundingDate?: T;
  taxSettings?:
    | T
    | {
        gstin?: T;
        businessName?: T;
        businessAddress?: T;
        businessState?: T;
        gstRatePercent?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  cashOnDelivery?: T;
  giftCards?: T;
  coupons?: T;
  backInStockAlerts?: T;
  recentlyViewed?: T;
  searchAutocomplete?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}